digiwiz/classroom/urls.py
from django.urls import include, path
from .views import classroom, staff, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'),

    path('staff/', include(([
        path('', staff.dashboard, name='dashboard'),
        path('account/', staff.account, name='account'),
        path('account/change-password/', staff.ChangePassword.as_view(), name='change_password'),
        path('admin-accounts/', staff.AdminListView.as_view(), name='admin_list'),
        path('admin-accounts/add/', staff.AdminCreateView.as_view(), name='admin_add'),
        path('admin-accounts/<int:pk>/delete/', staff.deactivate_admin, name='admin_deactivate'),
        path('course-requests/', staff.CourseRequestsView.as_view(), name='course_requests'),
        path('course-requests/accept/<int:course_pk>/', staff.accept_course, name='accept_course'),
        path('course-requests/reject/<int:course_pk>/', staff.reject_course, name='reject_course'),
        path('courses/', staff.CourseListView.as_view(), name='course_list'),
        path('courses/<int:course_pk>/delete/', staff.delete_course, name='course_delete'),
        path('get-user-activities/', staff.get_user_activities, name='get_user_activities'),
        path('get-course-status/', staff.get_course_status, name='get_course_status'),
        path('students/', staff.StudentListView.as_view(), name='student_list'),
        path('students/<int:pk>/delete/', staff.deactivate_student, name='teacher_deactivate'),
        path('subjects/', staff.SubjectListView.as_view(), name='subject_list'),
        path('subjects/add/', staff.SubjectCreateView.as_view(), name='subject_add'),
        path('subjects/<int:pk>/', staff.SubjectUpdateView.as_view(), name='subject_change'),
        path('subjects/<int:pk>/delete/', staff.delete_subject, name='subject_delete'),
        path('teachers/', staff.TeacherListView.as_view(), name='teacher_list'),
        path('teachers/<int:pk>/delete/', staff.deactivate_teacher, name='teacher_deactivate'),
        path('user-log/', staff.UserLogListView.as_view(), name='user_log_list'),
        path('user-log/<int:pk>/delete/', staff.delete_log, name='user_log_delete')
    ], 'classroom'), namespace='staff')),

    path('student/', include(([
        path('', students.MyCoursesListView.as_view(), name='mycourses_list'),
        path('change-password/', students.ChangePassword.as_view(), name='change_password'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/', students.take_quiz, name='take_quiz'),
        path('enroll/<int:pk>/', students.enroll, name='enroll'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('profile/', students.profile, name='profile'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('taken/<int:taken_pk>/quiz/<int:quiz_pk>/', students.taken_quiz_result, name='taken_quiz_detail'),
        path('unenroll/<int:pk>/', students.unenroll, name='unenroll'),
        path('view-file/<int:pk>/', students.file_view, name='view_file')
    ], 'classroom'), namespace='students')),

    path('teacher/', include(([
        path('', teachers.CourseListView.as_view(), name='course_change_list'),
        path('ajax/load-lessons/', teachers.load_lessons, name='ajax_load_lessons'),
        path('change-password/', teachers.ChangePassword.as_view(), name='change_password'),
        path('course/add/', teachers.CourseCreateView.as_view(), name='course_add'),
        path('course/<int:pk>/', teachers.CourseUpdateView.as_view(), name='course_change'),
        path('course/<int:pk>/delete/', teachers.delete_course,name='course_delete'),
        path('course/<int:course_pk>/lesson/<int:lesson_pk>/',
             teachers.edit_lesson, name='lesson_edit'),
        path('course/<int:course_pk>/lesson/<int:lesson_pk>/delete/',
             teachers.delete_lesson, name='lesson_delete'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/',
             teachers.edit_quiz, name='quiz_edit'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/question/add/',
             teachers.add_question, name='question_add'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/',
             teachers.edit_question, name='question_change'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/delete/',
             teachers.delete_question, name='question_delete'),
        path('enrollment-requests/', teachers.EnrollmentRequestsListView.as_view(),
             name='enrollment_requests_list'),
        path('enrollment-requests/accept/<int:taken_course_pk>', teachers.accept_enrollment,
             name='enrollment_accept'),
        path('enrollment-requests/reject/<int:taken_course_pk>', teachers.reject_enrollment,
             name='enrollment_reject'),
        path('files/', teachers.FilesListView.as_view(), name='file_list'),
        path('files/add/', teachers.add_files, name='file_add'),
        path('files/<int:file_pk>/delete/', teachers.delete_file,
             name='delete_file'),
        path('lesson/', teachers.LessonListView.as_view(), name='lesson_list'),
        path('lesson/add/', teachers.add_lesson, name='lesson_add'),
        path('lesson/<int:lesson_pk>/delete/', teachers.delete_lesson_from_list,
             name='delete_lesson_from_list'),
        path('profile/', teachers.profile, name='profile'),
        path('quiz/', teachers.QuizListView.as_view(), name='quiz_list'),
        path('quiz/add/', teachers.add_quiz, name='quiz_add'),
        path('quiz/<int:quiz_pk>/delete/', teachers.delete_quiz_from_list,
             name='delete_quiz_from_list'),
        path('quiz/<int:quiz_pk>/delete/', teachers.delete_quiz, name='quiz_delete'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:quiz_pk>/results/<int:student_pk>/taken/<int:taken_pk>',
             teachers.quiz_result_detail, name='quiz_result_detail')
    ], 'classroom'), namespace='teachers')),
]

digiwiz/digiwiz/urls.py
from ckeditor_uploader import views as uploader_views
from classroom.views import classroom, students, teachers
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.urls import include, path
from django.views.decorators.cache import never_cache
from . import settings


urlpatterns = [
    path('', include('classroom.urls')),
    path('about-us/', classroom.about, name='about_us'),
    path('activate-student/<str:uidb64>/<str:token>', students.activate, name='activate_student'),
    path('activate-teacher/<str:uidb64>/<str:token>', teachers.activate, name='activate_teacher'),
    path('browse-courses/', classroom.browse_courses, name='browse_courses'),
    path('browse-courses/<int:subject_pk>/', classroom.browse_courses_subject, name='browse_courses_subject'),
    path('ckeditor/upload/', uploader_views.upload, name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(uploader_views.browse), name='ckeditor_browse'),
    path('contact-us/', classroom.contact_us, name='contact_us'),
    path('course/details/<int:pk>/', classroom.CourseDetailView.as_view(), name='course_details'),
    path('course/details/<int:pk>/lesson', students.LessonListView.as_view(), name='lesson_list'),
    path('django-admin/', admin.site.urls),
    path('login/', classroom.login_view, name='login'),
    path('logout/', classroom.logout_view, name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='authentication/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('register/', classroom.register_page, name='register'),
    path('register/student/', students.register, name='student_register'),
    path('register/teacher/', teachers.register, name='teacher_register')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digiwiz/classroom/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils.html import escape, mark_safe
from sorl.thumbnail import ImageField
from star_ratings.models import Rating


class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        for field_name in ['first_name', 'last_name']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.title())

        super(User, self).save(*args, **kwargs)


class UserLog(models.Model):
    action = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    user_type = models.CharField(max_length=10)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_logs')

    def __str__(self):
        return f'{self.user.username}: {self.action}'


class Subject(models.Model):
    name = models.CharField(max_length=30)
    color = models.CharField(max_length=9, default='#007bff')

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        color = escape(self.color)
        html = f'<span class="badge badge-primary" style="background-color: {color}">{name}</span>'
        return mark_safe(html)


class Course(models.Model):
    title = models.CharField(max_length=100)
    code = models.CharField(max_length=20, unique=True)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='courses',
                              help_text='Recommended image resolution: 740px x 480px')
    status = models.CharField(max_length=10, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='courses')
    ratings = GenericRelation(Rating, related_query_name='courses')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Set every first letter to capital:
        setattr(self, 'title', getattr(self, 'title', False).title())
        # Set the course code to ALL CAPS
        setattr(self, 'code', getattr(self, 'code', False).upper())
        super(Course, self).save(*args, **kwargs)


class Lesson(models.Model):
    title = models.CharField(max_length=100)
    number = models.IntegerField()
    description = models.TextField(max_length=1000)
    content = RichTextUploadingField(external_plugin_resources=[(
        'youtube',
        '/static/classroom/vendor/ckeditor_plugins/youtube/youtube/',
        'plugin.js',
    )])
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        setattr(self, 'title', getattr(self, 'title', False).title())
        super(Lesson, self).save(*args, **kwargs)


class Quiz(models.Model):
    title = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='quizzes')
    lesson = models.OneToOneField(Lesson, on_delete=models.CASCADE, related_name='quizzes')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        setattr(self, 'title', getattr(self, 'title', False).title())
        super(Quiz, self).save(*args, **kwargs)


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='questions')
    text = models.CharField('Question', max_length=500)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    text = models.CharField('', max_length=500)
    is_correct = models.BooleanField('Correct answer', default=False)

    def __str__(self):
        return self.text


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    image = ImageField(default='profile_pics/default-user.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} - teacher'


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    image = ImageField(default='profile_pics/default-user.jpg', upload_to='profile_pics')
    courses = models.ManyToManyField(Course, through='TakenCourse')
    quizzes = models.ManyToManyField(Quiz, through='TakenQuiz')
    interests = models.ManyToManyField(Subject, related_name='interested_students')

    def get_unanswered_questions(self, quiz):
        answered_questions = self.quiz_answers \
            .filter(answer__question__quiz=quiz) \
            .values_list('answer__question__pk', flat=True)
        questions = quiz.questions.exclude(pk__in=answered_questions).order_by('id')
        return questions

    def __str__(self):
        return f'{self.user.username} - student'


class TakenCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='taken_courses')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='taken_courses')
    status = models.CharField(max_length=12, default='pending')
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.student.user.username}: {self.course.title}'


class TakenQuiz(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='taken_quizzes')
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name='taken_quizzes')
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='taken_quizzes')
    score = models.FloatField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.student.user.username}: {self.quiz.title}'


class StudentAnswer(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='quiz_answers')
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='+')


class MyFile(models.Model):
    file = models.FileField(upload_to='class_resources/')
    created_at = models.DateTimeField(auto_now_add=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='my_files')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='my_files')

    def __str__(self):
        return f'{self.file}'

digiwiz/classroom/views/raw_sql.py
def get_taken_quiz(student_id, taken_quiz_id):
    sql = (f'SELECT * FROM classroom_takenquiz tq '
           f'JOIN classroom_quiz q ON tq.quiz_id = q.id '
           f'JOIN classroom_question cq ON q.id = cq.quiz_id '
           f'JOIN classroom_answer ca on cq.id = ca.question_id '
           f'JOIN classroom_studentanswer cs on ca.id = cs.answer_id '
           f'WHERE tq.id = {taken_quiz_id} AND cs.student_id = {student_id} ')

    return sql


def get_popular_courses():
    sql = ('SELECT * FROM star_ratings_rating sr '
           'JOIN classroom_course c ON sr.object_id = c.id '
           'WHERE c.status = \'approved\' '
           'ORDER BY average DESC LIMIT 6')

    return sql

digiwiz/classroom/templates/classroom/teachers/course_add_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="login-page page-wrapper s-pd100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-6 col-sm-8">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'teachers:course_change_list' %}">My Courses</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Add a New Course</li>
                        </ol>
                    </nav><br>
                    <div class="login-form-area">
                        <h2 class="mb-3">Add a course</h2>
                        <form method="post" enctype="multipart/form-data" novalidate>
                            {% csrf_token %}
                            {{ form.media }}
                            {{ form|crispy }}
                            <center>
                                <button type="submit" class="btn btn-success">Save</button>
                                <a href="{% url 'teachers:course_change_list' %}" class="btn btn-danger" role="button">Cancel</a>
                            </center>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

digiwiz/classroom/templates/classroom/teachers/course_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="login-page page-wrapper s-pd100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-6 col-sm-8">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'teachers:course_change_list' %}">My Courses</a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ course.title }}</li>
                        </ol>
                    </nav><br>
                    <div class="login-form-area">
                        <h2>Edit a Course</h2>
                        <form method="post" enctype="multipart/form-data" novalidate>
                            {% csrf_token %}
                            {{ form.media }}
                            {{ form|crispy }}
                            <button type="submit" class="btn btn-success">Save changes</button>
                            <a href="{% url 'teachers:lesson_add' %}" class="btn btn-secondary" role="button">Add a Lesson</a>
                            <a href="{% url 'teachers:course_change_list' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
                            <a href="#" class="btn btn-danger float-right delete">Delete</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $(".delete").click(function () {
            swal({
                title: "Are you sure you want to delete this course?",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
            .then((willDelete) => {
                if (willDelete) {
                    window.location = "{% url 'teachers:course_delete' course.pk %}";
                }
            });
        });
    </script>
{% endblock %}

digiwiz/classroom/templates/classroom/teachers/enrollment_requests_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
    <section id="courses-section" class="popular-courses-area bg-white s-pd2">
        <div class="container">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                        <p{% if forloop.last %} class="mb-0"{% endif %}>{{ message }}</p>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="row justify-content-md-center">
                <div class="col-lg-8">
                    <div class="section-heading-area text-center">
                        <h2 class="section-heading text-capitalize">Student Enrollment Requests</h2>
                    </div><!--/.section-heading-area-->
                </div><!--/.col-lg-8-->
            </div><!--/.row-->
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-3">
                            <strong>Student</strong>
                        </div>
                        <div class="col-4">
                            <strong>Course</strong>
                        </div>
                        <div class="col-2">
                            <strong>Course Code</strong>
                        </div>
                        <div class="col-3">
                            <strong>Action</strong>
                        </div>
                    </div>
                </div>
                <div class="list-group list-group-flush list-group-formset">
                    {% for taken_course in taken_courses %}
                        <div class="list-group-item">
                            <div class="row">
                                <div class="col-3">
                                    {% thumbnail taken_course.student.image "40x40" crop="center" as im %}
                                        <img class="rounded-circle" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="course-owner">&nbsp;&nbsp;
                                    {% endthumbnail %}
                                    {{ taken_course.student.user.first_name }} {{ taken_course.student.user.last_name }}
                                </div>
                                <div class="col-4">
                                    <a href="{% url 'course_details' taken_course.course.pk %}">{{ taken_course.course.title }}</a>
                                </div>
                                <div class="col-2">
                                    {{ taken_course.course.code }}
                                </div>
                                <div class="col-3">
                                    <a href="{% url 'teachers:enrollment_accept' taken_course.pk %}" role="button" class="btn btn-primary">Accept Request</a>
                                    <a href="{% url 'teachers:enrollment_reject' taken_course.pk %}" role="button" class="btn btn-primary">Reject</a>
                                </div>

                            </div>
                        </div>
                    {% empty %}
                        <div class="list-group-item text-center">
                            <p class="text-muted font-italic mb-0">There are no enrollment requests right now.</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}

digiwiz/classroom/templates/classroom/teachers/quiz_add_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="login-page page-wrapper s-pd100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-6 col-sm-8">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_list' %}">My Quizzes</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Add a New Quiz</li>
                        </ol>
                    </nav><br>
                    <div class="login-form-area">
                        <h2 class="mb-3">Add a quiz</h2>
                        <form method="post" id="quizForm" data-lessons-url="{% url 'teachers:ajax_load_lessons' %}" novalidate>
                            {% csrf_token %}
                            {{ form|crispy }}
                            <center>
                                <button type="submit" class="btn btn-success">Save</button>
                                <a href="{% url 'teachers:quiz_list' %}" class="btn btn-danger" role="button">Cancel</a>
                            </center>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $("#id_course").change(function () {
            var url = $("#quizForm").attr("data-lessons-url");  // get the url of the `load_lessons` view
            var course_id = $(this).val();  // get the selected course ID from the HTML input

            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-lessons/)
                data: {
                    'course': course_id       // add the course id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `load_lessons` view function
                    $("#id_lesson").html(data);  // replace the contents of the lesson input with the data that came from the server
                }
            });

        });
    </script>
{% endblock %}

digiwiz/classroom/templates/classroom/teachers/quiz_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="login-page page-wrapper s-pd100">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 col-md-6 col-sm-8">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                                <p{% if forloop.last %} class="mb-0"{% endif %}>{{ message }}</p>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_list' %}">My Quizzes</a></li>
                            <li class="breadcrumb-item active" aria-current="page">{{ quiz.title }}</li>
                        </ol>
                    </nav><br>
                    <div class="login-form-area">
                        <h2 class="mb-3">{{ quiz.title }}</h2>
                        <a href="{% url 'teachers:quiz_results' quiz.pk %}" class="btn btn-primary float-right">View results</a>
                        <form method="post" novalidate>
                            {% csrf_token %}
                            {{ form|crispy }}
                            {# The course field will be ignored in the backend since it is not included in LessonEditForm class #}
                            <label for="course" class="col-form-label  requiredField">
                                Course<span class="asteriskField"></span>
                            </label>
                            <input type="text" class="textinput textInput form-control" value="{{ quiz.course.title }}" id="course" disabled>
                            <label for="lesson" class="col-form-label  requiredField">
                                Lesson<span class="asteriskField"></span>
                            </label>
                            <input type="text" class="textinput textInput form-control" value="{{ quiz.lesson.title }}" id="lesson" disabled>
                            <br>
                            <button type="submit" class="btn btn-success">Save changes</button>
                            <a href="{% url 'teachers:quiz_list' %}" class="btn btn-outline-secondary" role="button">Go Back</a>
                            <a href="#" class="btn btn-danger float-right delete">Delete</a>
                        </form>
                    </div>
                    <br><br>
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col-10">
                                    <strong>Questions</strong>
                                </div>
                                <div class="col-2">
                                    <strong>Choices</strong>
                                </div>
                            </div>
                        </div>
                        <div class="list-group list-group-flush list-group-formset">
                            {% for question in questions %}
                                <div class="list-group-item">
                                    <div class="row">
                                        <div class="col-10">
                                            <a href="{% url 'teachers:question_change' course.pk quiz.pk question.pk %}">{{ question.text }}</a>
                                        </div>
                                        <div class="col-2">
                                            {{ question.answers_count }}
                                        </div>
                                    </div>
                                </div>
                            {% empty %}
                                <div class="list-group-item text-center">
                                    <p class="text-muted font-italic mb-0">You haven't created any questions yet. Go ahead and <a href="{% url 'teachers:question_add' course.pk quiz.pk %}">add the first question</a>.</p>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="card-footer">
                            <a href="{% url 'teachers:question_add' course.pk quiz.pk %}" class="btn btn-primary btn-sm">Add question</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="login-page page-wrapper s-pd100">
        <div class="container">

        </div>
    </div>

    <script>
        $(".delete").click(function () {
            swal({
                title: "WARNING: Are you sure you want to delete this quiz?",
                text: "Once you delete this, you will never recover it.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        window.location = "{% url 'teachers:quiz_delete' quiz.pk %}";
                    }
                });
        });
    </script>
{% endblock %}