digiwiz/classroom/urls.py
from django.urls import include, path
from .views import classroom, staff, students, teachers

urlpatterns = [
    path('', classroom.home, name='home'),

    path('staff/', include(([
        path('', staff.dashboard, name='dashboard'),
        path('account/', staff.account, name='account'),
        path('account/change-password/', staff.ChangePassword.as_view(), name='change_password'),
        path('admin-accounts/', staff.AdminListView.as_view(), name='admin_list'),
        path('admin-accounts/add/', staff.AdminCreateView.as_view(), name='admin_add'),
        path('admin-accounts/<int:pk>/delete/', staff.deactivate_admin, name='admin_deactivate'),
        path('course-requests/', staff.CourseRequestsView.as_view(), name='course_requests'),
        path('course-requests/accept/<int:course_pk>/', staff.accept_course, name='accept_course'),
        path('course-requests/reject/<int:course_pk>/', staff.reject_course, name='reject_course'),
        path('courses/', staff.CourseListView.as_view(), name='course_list'),
        path('courses/<int:course_pk>/delete/', staff.delete_course, name='course_delete'),
        path('get-user-activities/', staff.get_user_activities, name='get_user_activities'),
        path('get-course-status/', staff.get_course_status, name='get_course_status'),
        path('students/', staff.StudentListView.as_view(), name='student_list'),
        path('students/<int:pk>/delete/', staff.deactivate_student, name='teacher_deactivate'),
        path('subjects/', staff.SubjectListView.as_view(), name='subject_list'),
        path('subjects/add/', staff.SubjectCreateView.as_view(), name='subject_add'),
        path('subjects/<int:pk>/', staff.SubjectUpdateView.as_view(), name='subject_change'),
        path('subjects/<int:pk>/delete/', staff.delete_subject, name='subject_delete'),
        path('teachers/', staff.TeacherListView.as_view(), name='teacher_list'),
        path('teachers/<int:pk>/delete/', staff.deactivate_teacher, name='teacher_deactivate'),
        path('user-log/', staff.UserLogListView.as_view(), name='user_log_list'),
        path('user-log/<int:pk>/delete/', staff.delete_log, name='user_log_delete')
    ], 'classroom'), namespace='staff')),

    path('student/', include(([
        path('', students.MyCoursesListView.as_view(), name='mycourses_list'),
        path('change-password/', students.ChangePassword.as_view(), name='change_password'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/', students.take_quiz, name='take_quiz'),
        path('enroll/<int:pk>/', students.enroll, name='enroll'),
        path('interests/', students.StudentInterestsView.as_view(), name='student_interests'),
        path('profile/', students.profile, name='profile'),
        path('taken/', students.TakenQuizListView.as_view(), name='taken_quiz_list'),
        path('taken/<int:taken_pk>/quiz/<int:quiz_pk>/', students.taken_quiz_result, name='taken_quiz_detail'),
        path('unenroll/<int:pk>/', students.unenroll, name='unenroll'),
        path('view-file/<int:pk>/', students.file_view, name='view_file')
    ], 'classroom'), namespace='students')),

    path('teacher/', include(([
        path('', teachers.CourseListView.as_view(), name='course_change_list'),
        path('ajax/load-lessons/', teachers.load_lessons, name='ajax_load_lessons'),
        path('change-password/', teachers.ChangePassword.as_view(), name='change_password'),
        path('course/add/', teachers.CourseCreateView.as_view(), name='course_add'),
        path('course/<int:pk>/', teachers.CourseUpdateView.as_view(), name='course_change'),
        path('course/<int:pk>/delete/', teachers.delete_course,name='course_delete'),
        path('course/<int:course_pk>/lesson/<int:lesson_pk>/',
             teachers.edit_lesson, name='lesson_edit'),
        path('course/<int:course_pk>/lesson/<int:lesson_pk>/delete/',
             teachers.delete_lesson, name='lesson_delete'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/',
             teachers.edit_quiz, name='quiz_edit'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/question/add/',
             teachers.add_question, name='question_add'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/',
             teachers.edit_question, name='question_change'),
        path('course/<int:course_pk>/quiz/<int:quiz_pk>/question/<int:question_pk>/delete/',
             teachers.delete_question, name='question_delete'),
        path('enrollment-requests/', teachers.EnrollmentRequestsListView.as_view(),
             name='enrollment_requests_list'),
        path('enrollment-requests/accept/<int:taken_course_pk>', teachers.accept_enrollment,
             name='enrollment_accept'),
        path('enrollment-requests/reject/<int:taken_course_pk>', teachers.reject_enrollment,
             name='enrollment_reject'),
        path('files/', teachers.FilesListView.as_view(), name='file_list'),
        path('files/add/', teachers.add_files, name='file_add'),
        path('files/<int:file_pk>/delete/', teachers.delete_file,
             name='delete_file'),
        path('lesson/', teachers.LessonListView.as_view(), name='lesson_list'),
        path('lesson/add/', teachers.add_lesson, name='lesson_add'),
        path('lesson/<int:lesson_pk>/delete/', teachers.delete_lesson_from_list,
             name='delete_lesson_from_list'),
        path('profile/', teachers.profile, name='profile'),
        path('quiz/', teachers.QuizListView.as_view(), name='quiz_list'),
        path('quiz/add/', teachers.add_quiz, name='quiz_add'),
        path('quiz/<int:quiz_pk>/delete/', teachers.delete_quiz_from_list,
             name='delete_quiz_from_list'),
        path('quiz/<int:quiz_pk>/delete/', teachers.delete_quiz, name='quiz_delete'),
        path('quiz/<int:pk>/results/', teachers.QuizResultsView.as_view(), name='quiz_results'),
        path('quiz/<int:quiz_pk>/results/<int:student_pk>/taken/<int:taken_pk>',
             teachers.quiz_result_detail, name='quiz_result_detail')
    ], 'classroom'), namespace='teachers')),
]

digiwiz/digiwiz/urls.py
from ckeditor_uploader import views as uploader_views
from classroom.views import classroom, students, teachers
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from django.urls import include, path
from django.views.decorators.cache import never_cache
from . import settings


urlpatterns = [
    path('', include('classroom.urls')),
    path('about-us/', classroom.about, name='about_us'),
    path('activate-student/<str:uidb64>/<str:token>', students.activate, name='activate_student'),
    path('activate-teacher/<str:uidb64>/<str:token>', teachers.activate, name='activate_teacher'),
    path('browse-courses/', classroom.browse_courses, name='browse_courses'),
    path('browse-courses/<int:subject_pk>/', classroom.browse_courses_subject, name='browse_courses_subject'),
    path('ckeditor/upload/', uploader_views.upload, name='ckeditor_upload'),
    path('ckeditor/browse/', never_cache(uploader_views.browse), name='ckeditor_browse'),
    path('contact-us/', classroom.contact_us, name='contact_us'),
    path('course/details/<int:pk>/', classroom.CourseDetailView.as_view(), name='course_details'),
    path('course/details/<int:pk>/lesson', students.LessonListView.as_view(), name='lesson_list'),
    path('django-admin/', admin.site.urls),
    path('login/', classroom.login_view, name='login'),
    path('logout/', classroom.logout_view, name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='authentication/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('register/', classroom.register_page, name='register'),
    path('register/student/', students.register, name='student_register'),
    path('register/teacher/', teachers.register, name='teacher_register')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digiwiz/templates/403_csrf.html
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from bdevs.net/edulab/edulab/404.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 12 May 2019 04:51:17 GMT -->
<head>
    <!--========= Basic Page Needs =========-->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!--========== Specific Meta ==========-->
    <meta name="description" content="Online Education template Based on HTML5.">
    <meta name="keywords" content="HTML5, Template, Design, Development, education, edulab, online cources, training, online education, best education template">

    <!--======== Page Title===========-->
    <title>403 Forbidden</title>

    <!--========== Favicons =========-->
    <link rel="shortcut icon" href="/static/images/DW.png">

    <!--======== Font icon Css ============-->
    <link href="/static/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/themify-icons.css" rel="stylesheet">

    <!--======= Bootstrap Main Css =============-->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!--====== Plugins Css ================-->
    <link href="/static/css/plugins.css" rel="stylesheet">

    <!--====== Custom CSS for themes =======-->
    <link href="/static/style.css" rel="stylesheet">

    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <script src="/static/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>

    <!--=======Error Page
    ====================================-->
    <div class="error-page page-wrapper s-pd145">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-sm-10">
                    <div class="error-page-content">
                        <div class="not-found">403</div>
                        <h3>Access Forbidden</h3>
                        <p>CSRF verification failed. Request Aborted.</p>
                        <div class="group-btn">
                            <a href="{% url 'home' %}" class="btn btn-default btn-primary">BACK TO HOME</a>
                        </div>
                    </div><!--/.error-page-content-->
                </div><!--/.col-sm-8-->
            </div><!--/.row-->
        </div><!--/.container-->
    </div><!--/.error-page-->

    <!--=========== JS FILE DECLARATION  ==============-->
    <!-- jQuery Latest Version -->
    <script src="/static/js/jquery-v3.2.1.min.js"></script>
    <!-- PopperJS -->
    <script src="/static/js/popper.min.js"></script>
    <!-- Bootstrap framework JS -->
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- All JS plugins included in this file. -->
    <script src="/static/js/plugins.js"></script>
    <!-- Main JS file that contents all jQuery Plugins activation. -->
    <script src="/static/js/main.js"></script>
</body>

<!-- Mirrored from bdevs.net/edulab/edulab/404.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 12 May 2019 04:51:17 GMT -->
</html>

digiwiz/templates/base.html
{% load crispy_forms_tags %}{% load static %}{% load thumbnail %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <meta name="description" content="Online Education template Based on HTML5.">
    <meta name="keywords" content="HTML5, Template, Design, Development, education, edulab, online cources, training, online education, best education template">

    <title>{% if title %}
      E_elimu :{{ title }}
    {% else %}
        E_elimu
    {% endif %}</title>

    <link rel="icon" href="{% static 'images/DW.png' %}">

    <!--======== Font icon Css ============-->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/themify-icons.css' %}" rel="stylesheet">

    <!--======= Bootstrap Main Css =============-->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!--====== Plugins Css ================-->
    <link href="{% static 'css/plugins.css' %}" rel="stylesheet">

    <!--====== Custom CSS for themes =======-->
    <link href="{% static 'style.css' %}" rel="stylesheet">
    <link href="{% static 'btn.css' %}" rel="stylesheet">
    <link href="{% static 'stars.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.4.1.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    <style>{% for subject in subjects %}
        .btn-{{ subject.name.lower }} {
            background-color: transparent;
            border: 1px solid {{ subject.color }};
            border-radius: 30px;
            font-size: 12px;
            padding: 15px 35px;
            text-transform: uppercase;
            font-weight: bold;
            letter-spacing: 1px;
            color: #ffffff;
        }
        .btn-primary-{{ subject.name.lower }} {
            background-color: {{ subject.color }};
            border-color: {{ subject.color }};
        }
        .btn-{{ subject.name.lower }}:hover {
            background-color: {{ subject.color }};
            border-color: {{ subject.color }};
            color: #ffffff;
        }
        .btn-primary-{{ subject.name.lower }}:hover {
            background-color: transparent;
            color: {{ subject.color }};
            border-color: {{ subject.color }};
        }
    {% endfor %}</style>
</head>
<body>
<!--====Header Area
====================================-->
<header id="site-header" class="header-area">
    <div class="header-inner">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="logo-menu-wrap hidden-xs hidden-sm">
                        <div class="logo">
                            <a href="{% url 'home' %}">
                              <h1>E_elimu</h1>
                            </a>
                        </div><!--/.logo-->

                        <nav class="menu">
                            <ul id="nav" align="center">
                                {% if user.is_authenticated %}
                                    {% if user.is_student %}
                                        {% if title != 'Browse Courses' %}
                                            <li>
                                                <form class="product-search-form" method="get" action="{% url 'browse_courses' %}" style="position: absolute; left: -280px; top: 10px;" novalidate>
                                                    <div class="form-group"style="width: 300px;  height: 50px; " >
                                                        <input type="text" name="search" placeholder="Type keyword here" class="textinput textInput form-controllar" required id="id_search" style="height: 50px; width: 230px">
                                                        <input type="image" src="{% static 'images/icon/search.png' %}" style="height:30px; width:30px; margin: 8px;" align="right" alt="Search" title="Search">
                                                    </div>
                                                </form>
                                            </li>
                                        {% endif %}

                                        <li><a href="{% url 'browse_courses' %}">Browse Courses</a></li>
<li class="dropdown-trigger">
                                            {% thumbnail user.student.image "40x40" crop="center" as im %}
                                                <img class="rounded-circle" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="course-owner">
                                            {% endthumbnail %}&nbsp;&nbsp;
                                            <a href="#">{{ user.first_name }}</a>
                                            <ul class="dropdown-content">
                                                <li><a href="{% url 'students:profile' %}">My Profile</a></li>
                                                <li><a href="{% url 'students:mycourses_list' %}">My Courses</a></li>
                                                <li><a href="{% url 'students:taken_quiz_list' %}">My Quizzes</a></li>
                                                <li class="login"><a href="{% url 'logout' %}">Logout</a></li>
                                            </ul>
                                        </li>
                                    {% elif user.is_teacher %}


                                        <li ><a href="{% url 'browse_courses' %}">Browse Courses</a></li>
                                        <li class="login">
                                            <a href="{% url 'teachers:enrollment_requests_list' %}">Enrollment Requests
                                                {% if enrollment_request_count > 0 %}
                                                    <sup>
                                                            <span style="background-color: red; color: white; padding: 2px; border-radius: 3px;">
                                                                &nbsp;<b>{{ enrollment_request_count }}</b>&nbsp;
                                                            </span>
                                                    </sup>
                                                {% endif %}
                                            </a>
                                        </li>
                                        <li class="dropdown-trigger">
                                            {% thumbnail user.teacher.image "40x40" crop="center" as im %}
                                                <img class="rounded-circle" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="course-owner">
                                            {% endthumbnail %}&nbsp;&nbsp;
                                            <a href="#">{{ user.first_name }}</a>

                                            <ul class="dropdown-content">
                                                <li><a href="{% url 'teachers:profile' %}">My Profile</a></li>
                                                <li><a href="{% url 'teachers:course_change_list' %}">My Courses</a></li>
                                                <li><a href="{% url 'teachers:lesson_list' %}">My Lessons</a></li>
                                                <li><a href="{% url 'teachers:quiz_list' %}">My Quizzes</a></li>
                                                <li><a href="{% url 'teachers:file_list' %}">My Files</a></li>
                                                <li class="login"><a href="{% url 'logout' %}">Logout</a></li>
                                            </ul>
                                        </li>
                                    {% elif user.is_staff %}
                                        <li><a>{{ user.first_name }}</a></li>
                                        <li class="login"><a href="{% url 'logout' %}">Logout</a></li>
                                    {% endif %}

                                    </ul>
                                    </nav>

                                {% else %}
                                    <li class="login"><a href="{% url 'home' %}">Home</a></li>
                                    <li class="login"><a href="{% url 'browse_courses' %}">Courses</a></li>
                                    <li class="login"><a href="{% url 'about_us' %}">About Us</a></li>
                                    <li class="login"><a href="{% url 'register' %}">Register</a></li>
                                    <li class="login"><a href="{% url 'login' %}">Login</a></li>
                                    </ul>
                                    </nav><!--/.menu-->
                                    <div class="register-contact-nav pull-right">
                                        <a class="register-contact-nav login btn btn-default " href="{% url 'contact_us' %}" hidden>contact</a> <a class="register-contact-nav login btn btn-default " href="{% url 'contact_us' %}">contact</a>
                                    </div><!--/.register-contact-nav-->
                                {% endif %}
                    </div><!--/.logo-menu-wrap-->
                </div><!--/.col-lg-12-->
            </div><!--/.row-->
        </div><!--/.container-fluid-->
    </div><!--/.headier-inner-->

    <div id="sticky-header"></div><!--/#sticky-header-->

    <!--Mobile Menu-->
    <div class="mobile-menu">
        <a class="mobile-logo" href="index.html"><img src="{% static 'images/digiwiz.png' %}" alt="logo" height="40"></a>
    </div>
</header><!--/.header-area-->

{% block content %}
{% endblock %}

<!-- Start footer area -->
<footer id="footer" class="site-footer">
    {% block join_us %}
    {% endblock %}
    <!-- Start footer widgets area -->
    <div class="footer-widgets-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6 col-6">
                    <div class="footer-widget">
                        <h4 class="footer-title">Quick Links</h4>
                        <ul class="footer-widget-list list-unstyled">
                            <li><a href="#">Help Desk</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">User Reviews</a></li>
                            <li><a href="#">Client Area</a></li>
                            <li><a href="#">About Us</a></li>
                        </ul>
                    </div><!--/.footer-widget-->
                </div><!--/.col-lg-3-->
                <div class="col-lg-3 col-sm-6 col-6">
                    <div class="footer-widget">
                        <h4 class="footer-title">Navigation</h4>
                        <ul class="footer-widget-list list-unstyled">
                            <li><a href="#">Features</a></li>
                            <li><a href="#">Screen Shot</a></li>
                            <li><a href="#">How it Works</a></li>
                            <li><a href="#">Testimonial</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div><!--/.footer-widget-->
                </div><!--/.col-lg-3-->
                <div class="col-lg-6 col-sm-12">
                    <div class="footer-newsletter footer-widget">
                        <h4 class="footer-title">Newsletter</h4>
                        <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur sint occaecat.</p>
                        <form class="newsletter-form">
                            <div class="form-group">
                                <input class="form-control" type="email" placeholder="Your email address">
                                <button type="submit" class="btn btn-default btn-primary">Subscribe</button>
                            </div>
                        </form>
                    </div><!--/.footer-newsletter-->
                </div><!--/.col-lg-6-->
            </div><!--/.row-->
        </div><!--/.container-->
    </div><!-- End footer widgets area -->

    <!-- Start footer copyright area -->
    <div class="footer-copyright-area bg-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright text-center">
                        Copyright © 2019 E_elimu</a>. All rights reserved.
                    </div>
                </div>
            </div><!--/.row-->
        </div><!--/.container-->
    </div><!--End footer copyright area -->
</footer><!--End footer area -->

<!-- All JS files are included here.
============================================== -->

<!-- jQuery Latest Version -->
<script src="{% static 'js/jquery-v3.2.1.min.js' %}"></script>
<!-- Popper JS -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap framework JS -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- All JS plugins included in this file. -->
<script src="{% static 'js/plugins.js' %}"></script>
<!-- Main JS file that contents all jQuery Plugins activation. -->
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>